let current=null, config=null;
const $=id=>document.getElementById(id);
const api=localStorage.getItem('prglmApi')||location.origin;
function value(id){let e=$(id);return e.type==='checkbox'?e.checked:e.value===''?null:e.type==='number'?Number(e.value):e.value}
async function generate(){let fields=['prompt','temperature','seed','max_tokens','max_cycles','repeats','forced_region','recurrence_override','fatigue_strength','recovery','recurrence','accumulation','fatigue','stochastic','comparison'];let body=Object.fromEntries(fields.map(k=>[k,value(k)]));$('status').textContent='Generating…';try{let r=await fetch(api+'/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data=await r.json();if(!r.ok)throw Error(data.detail||r.status);current=data.runs[0].prg;$('transformer').textContent=data.runs[0].transformer.text;$('prg').textContent=current.text;$('prg_v1').textContent=data.runs[0].prg_v1?.text||'Select byte-256 v1 study to generate.';if(data.runs[0].prg_v1&&window.showV1Run)window.showV1Run(data.runs[0].prg_v1);$('variation').textContent=`${data.runs.length} runs · ${new Set(data.runs.map(x=>x.prg.completion)).size} unique PRG-v0 completions`;renderTimeline();$('status').textContent='Done'}catch(e){$('status').textContent=e.message+' · For live generation run the local FastAPI server.'}}
function renderTimeline(){let tl=current.timeline;$('token_step').max=Math.max(0,tl.length-1);$('timeline').replaceChildren();tl.forEach((t,i)=>{let d=document.createElement('details');d.innerHTML=`<summary>Token ${i+1}: ${escapeHTML(t.token)} · ${t.steps.map(s=>'R'+s.active.join(',R')).join(' → ')}</summary>`;t.steps.forEach(s=>{let p=document.createElement('p');p.textContent=`Cycle ${s.cycle}: active ${s.active.map(j=>'R'+j).join(', ')} | routes ${s.active.map(j=>['LOCAL','NEIGHBOR','RETURN','OUTPUT'][s.chosen_route[j]]).join(', ')} | fatigue ${s.active.map(j=>s.fatigue[j].toFixed(2)).join(', ')}`;d.append(p)});$('timeline').append(d)});drawGraph()}
function escapeHTML(x){return x.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function drawGraph(){if(!current)return;let ti=+$('token_step').value,steps=current.timeline[ti].steps;$('cycle_step').max=Math.max(0,steps.length-1);let ci=Math.min(+$('cycle_step').value,steps.length-1),s=steps[ci],svg=$('graph');svg.replaceChildren();$('step_label').textContent=`Token ${ti+1} (${current.timeline[ti].token}) · cycle ${ci+1}`;let n=s.activation.length,pts=Array.from({length:n},(_,i)=>[400+145*Math.cos(i*2*Math.PI/n),180+135*Math.sin(i*2*Math.PI/n)]);function node(tag,attr){let x=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attr).forEach(([k,v])=>x.setAttribute(k,v));svg.append(x);return x}for(let i=0;i<n;i++){let j=(i+1)%n;node('line',{x1:pts[i][0],y1:pts[i][1],x2:pts[j][0],y2:pts[j][1],stroke:'#406279','stroke-width':2})}for(let i=0;i<n;i++){let active=s.activation[i]>.05;node('circle',{cx:pts[i][0],cy:pts[i][1],r:24+Math.min(20,s.activation[i]*8),fill:active?'#2dc9af':'#384b60',stroke:s.chosen_route[i]===3?'#ffc857':'none','stroke-width':4});let t=node('text',{x:pts[i][0],y:pts[i][1]+5,fill:'white','text-anchor':'middle'});t.textContent='R'+i;let tip=document.createElementNS('http://www.w3.org/2000/svg','title');tip.textContent=`activation ${s.activation[i].toFixed(2)} fatigue ${s.fatigue[i].toFixed(2)} recurrence ${s.recurrence_probability[i].toFixed(2)} route ${['LOCAL','NEIGHBOR','RETURN','OUTPUT'][s.chosen_route[i]]}`;svg.append(tip)}}
async function bench(){try{let response=await fetch(api+'/api/benchmarks').catch(()=>null);if(!response||!response.ok)response=await fetch('results.json');let data=await response.json();config=data.config;let tbody=$('bench');tbody.replaceChildren();(data.results||[]).forEach(x=>{let row=tbody.insertRow();[x.model,x.val_ppl?.toFixed(2),x.parameters,(x.serialized_bytes/1e6).toFixed(3),(x.packed_bytes/1e6).toFixed(3),x.training_tokens_per_sec?.toFixed(1)].forEach(v=>{let c=row.insertCell();c.textContent=v})});$('history').textContent=(data.results||[]).map(x=>`${x.model}: ${x.history.map(h=>h.train_loss.toFixed(2)).join(' → ')}`).join('\n');drawBench(data)}catch(e){$('history').textContent=e.message}}
$('generate').onclick=generate;$('token_step').oninput=()=>{$('cycle_step').value=0;drawGraph()};$('cycle_step').oninput=drawGraph;bench();
const drawBase=drawGraph;
drawGraph=()=>{drawBase();if(!current)return;let ti=+$('token_step').value,ci=+$('cycle_step').value,s=current.timeline[ti].steps[ci],n=s.activation.length,svg=$('graph');let names=['LOCAL','NEIGHBOR','RETURN','OUTPUT'];let path=[];s.active.forEach(i=>{let a=s.chosen_route[i],j=s.destination[i]<0?null:s.destination[i];path.push(`R${i} → ${j===null?'OUTPUT':`R${j}`} (${names[a]})`);if(j!==null&&j!==i){let line=document.createElementNS('http://www.w3.org/2000/svg','line');let p=k=>[400+145*Math.cos(k*2*Math.PI/n),180+135*Math.sin(k*2*Math.PI/n)];line.setAttribute('x1',p(i)[0]);line.setAttribute('y1',p(i)[1]);line.setAttribute('x2',p(j)[0]);line.setAttribute('y2',p(j)[1]);line.setAttribute('stroke','#ffc857');line.setAttribute('stroke-width','5');line.setAttribute('opacity','.7');svg.prepend(line)}});$('step_label').textContent+=` · ${path.join(' | ')}`};
fetch('sample.json').then(r=>r.ok?r.json():null).then(data=>{if(!data)return;current=data.runs[0].prg;$('transformer').textContent=data.runs[0].transformer.text;$('prg').textContent=current.text;$('status').textContent='Saved sample shown. Generate uses the local API.';renderTimeline()}).catch(()=>{});
function chart(id,series,labels){let c=$(id),g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#0d1826';g.fillRect(0,0,w,h);let all=series.flatMap(s=>s.values),lo=Math.min(0,...all),hi=Math.max(1,...all);g.strokeStyle='#52677a';g.beginPath();g.moveTo(42,15);g.lineTo(42,h-34);g.lineTo(w-10,h-34);g.stroke();g.fillStyle='#a9bfcd';g.font='12px system-ui';g.fillText(hi.toFixed(1),3,20);g.fillText(lo.toFixed(1),3,h-34);series.forEach((s,k)=>{g.strokeStyle=s.color||['#2dc9af','#ffc857','#ef6f83','#8ab4f8'][k%4];g.fillStyle=g.strokeStyle;g.beginPath();s.values.forEach((v,i)=>{let x=50+i*(w-70)/Math.max(1,s.values.length-1),y=h-35-(v-lo)/(hi-lo)*(h-55);if(i===0)g.moveTo(x,y);else g.lineTo(x,y);if(s.points)g.fillRect(x-3,y-3,6,6)});g.stroke();g.fillText(s.name||'',50+(k%2)*210,20+Math.floor(k/2)*15)});if(labels)g.fillText(labels,50,h-8)}
function drawBench(data){let rows=data.results||[];chart('loss_chart',rows.map((r,i)=>({name:r.model,values:r.history.map(h=>h.train_loss),color:['#2dc9af','#ffc857','#ef6f83','#8ab4f8'][i]})),'training step →');chart('ppl_chart',rows.map((r,i)=>({name:r.model,values:[r.val_ppl],points:true,color:['#2dc9af','#ffc857','#ef6f83','#8ab4f8'][i]})),'validation PPL');scatterSize(rows)}
function scatterSize(rows){let c=$('size_chart'),g=c.getContext('2d'),w=c.width,h=c.height;g.fillStyle='#0d1826';g.fillRect(0,0,w,h);let maxX=Math.max(...rows.map(r=>r.serialized_bytes/1e6),1),maxY=Math.max(...rows.map(r=>r.val_ppl),1);g.strokeStyle='#52677a';g.beginPath();g.moveTo(42,15);g.lineTo(42,h-34);g.lineTo(w-10,h-34);g.stroke();g.fillStyle='#a9bfcd';g.fillText('serialized MB →',50,h-8);rows.forEach((r,i)=>{let x=50+(r.serialized_bytes/1e6)/maxX*(w-70),y=h-35-r.val_ppl/maxY*(h-55);g.fillStyle=['#2dc9af','#ffc857','#ef6f83','#8ab4f8'][i%4];g.beginPath();g.arc(x,y,6,0,Math.PI*2);g.fill();g.fillText(r.model,x+8,y-5)})}
function drawTrajectoryStats(){if(!current)return;let steps=current.timeline.flatMap(t=>t.steps),n=steps[0].activation.length,visits=Array(n).fill(0),fatigue=[],entropy=[],cycles=current.timeline.map(t=>t.steps.filter(s=>s.active.length).length);steps.forEach(s=>{s.active.forEach(i=>{visits[i]++;fatigue.push(s.fatigue[i]);let p=s.route_probability[i];entropy.push(-p.reduce((a,v)=>a+v*Math.log(Math.max(v,1e-12)),0))})});chart('region_chart',[{name:'visits by region',values:visits,points:true}],`R0 → R${n-1}`);$('trajectory_stats').textContent=`Trajectory length: ${cycles.join(', ')} · mean routing entropy: ${(entropy.reduce((a,b)=>a+b,0)/Math.max(1,entropy.length)).toFixed(2)} · mean active-region fatigue: ${(fatigue.reduce((a,b)=>a+b,0)/Math.max(1,fatigue.length)).toFixed(2)}`}
const renderBase=renderTimeline;renderTimeline=()=>{renderBase();drawTrajectoryStats()};
